### ISSUE TITLE
Nestjs 10 support

### ISSUE THREAD

**Issue by amirValibeigi** [squareboat/nest-storage#18]
Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.7.0 || ^7.0.0 || ^8.0.0 || ^9.0.0" from @squareboat/nest-storage@0.1.5
npm ERR! node_modules/@squareboat/nest-storage
npm ERR!   @squareboat/nest-storage@"^0.1.5" from the root project

**Comment by vinayak25** [comment]
This is resolved!
