### ISSUE TITLE
Nestjs 8 suport

### ISSUE THREAD

**Issue by cambagulung** [squareboat/nest-storage#7]
npm ERR! Found: @nestjs/common@8.0.5
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.7.0 || ^7.0.0" from @squareboat/nest-storage@0.1.0
npm ERR! node_modules/@squareboat/nest-storage
npm ERR!   @squareboat/nest-storage@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by micalevisk** [comment]
https://github.com/squareboat/nest-storage/blob/05259ff0b89029e78dd88bace306b65397457357/package.json#L48-L49

**Comment by micalevisk** [comment]
looks like this will be addressed in the next release

https://github.com/squareboat/nest-storage/blob/add9803f5a2b56f9fe20f0de540361bcb1425052/package.json#L48-L50

:fire:

**Comment by vinayak25** [comment]
Hello everyone, package support for NestJS 8 is already live on V0.1.1
